<?xml version="1.0"?>
<package format="2">
  <name>vrx_controller_ros</name>
  <version>0.1.0</version>
  <description>ROS Melodic integration for the VRX 2019 station-keeping controller.</description>
  <maintainer email="retief@example.invalid">VRX Record Lab</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>geographic_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rospy</depend>
  <depend>robot_localization</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
  </export>
</package>
